kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ssd1
            - name: NFS_SERVER
              value: 192.168.1.101
            - name: NFS_PATH
              value: /mnt/extusb/kube
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.101
            path: /mnt/extusb/kube
