apiVersion: v1
kind: Service
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
  selector:
    service: cadvisor
  type: NodePort
